config/routes.rb
Rails.application.routes.draw do
  get 'employees/index'

  root 'employees#index'

  resources :employees, only: [] do
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end
end

app/models/employee.rb
class Employee < ActiveRecord::Base

  has_many :votes, dependent: :destroy

  def self.find_employees
    response = HTTParty.get("https://api.myjson.com/bins/16roa3")
    team_members = JSON.parse(response.body)

    team_members.map do |atr|
      team_member = Employee.find_or_create_by(g2employee_id:atr['id']) do |employee|
        employee.name = atr['name']
        employee.image_url = atr['image_url']
        employee.title = atr['title']
        employee.bio = atr['bio']
      end
      team_member
    end
  end

  def up_votes
    votes.where(value: 1).count
  end

  def down_votes
    votes.where(value: -1).count
  end

  def points
    votes.sum(:value)
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :employee

  validates :value, inclusion: { in: [-1,1], message: "%{value} is not a valid vote." }, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_filter :set_employees

  def index
  end

  private

  def set_employees
    @employees = Employee.all

    if @employees.empty?
      Employee.find_employees
    end
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def up_vote
    update_vote(1)
    redirect_to :back
  end

  def down_vote
    update_vote(-1)
    redirect_to :back
  end

  private

  def update_vote(new_value)
    @employee = Employee.find(params[:employee_id])
    @vote = Vote.create(value: new_value, employee: @employee)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/employees/index.html.erb
<div class="row hero-section">
  <div class="hero-section-text">
    <h1>G2 Crowd Team Roster</h1>
  </div>
  <hr>
</div>

<div class="section">
  <% @employees.each do |employee| %>
    <div class="row">
      <div class="small-12 medium-3 columns">
        <%= image_tag(employee['image_url'], class: 'employee_photo') %>
      </div>
      <div class="small-12 medium-9 columns">
        <%= content_tag(:h3, employee['name'], class: 'employee_name') %>
        <%= content_tag(:h4, employee['title'], class: 'employee_title') %>
        <%= content_tag(:p, employee['bio'], class: 'employee_bio') %>
        <%= render partial: 'votes/voter', locals: { employee: employee } %>
      </div>
    </div>
    <hr>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "G2 Teamvotes" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/votes/_voter.html.erb
<div class="row">
  <div class="small-12 columns">
    <p>
      <strong>Want to work with <%= employee.name %>?</strong>
      <%= link_to(raw("<span class='thumb-button'> #{image_tag('thumbs-up.svg', class: 'thumbs-up')} Yes!</span>"), employee_up_vote_path(employee), method: :post ) %>
    </p>
    <p><%= pluralize(employee.up_votes, 'visitor') %> said "Yes!"</p>
  </div>
</div>